config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
 
  resources :statuses
 

  resources :users

  root              'static_pages#home'
  get '/help'    => 'static_pages#help'
  get '/about'   => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
 get 'signup'    => 'users#new'
 get 'login'     => 'sessions#new'
 post 'login'    => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
resources :microposts
resources :images

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  mount_uploader :picture, PictureUploader
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }
	  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
						format: { with: VALID_EMAIL_REGEX },
						uniqueness: { case_sensitive: false }
	  has_secure_password
  validates :password, length: { minimum: 6 } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  helper_method :current_user
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
  	redirect_to '/login' unless current_user
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController


	def index
		@images = Image.all
	end
	def new
		@image = Image.new
	end
	def create
		@image = Image.new(image_params)
		if @image.save
			redirect_to "/images/index"
		else
			redirect_to "/"
		end
	end
	def show
		@image = Image.find(params[:id])
	end	
	
	private
	def image_params
		params.require(:image).permit(:content, :picture)
	end


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

	def index
		@microposts = Micropost.all
	end
	def new
		@micropost = Micropost.new
	end
	def create
		@micropost = Micropost.new(micropost_params)
		if @micropost.save
			redirect_to "/microposts/index"
		else
			redirect_to "/"
		end
	end
	def show
		@micropost = Micropost.find(params[:id])
	end	
	
	private
	def micropost_params
		params.require(:micropost).permit(:content, :picture)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
    
  end
  def create
    @user = User.find_by(email: params[:session][:email])
    if
      @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home

	end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
    http_basic_authenticate_with name:'andevl', password: 'foobar', 
                except:[:index, :show]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status }
        format.json { render :show, status: :created, location: @status }
      flash[:notice] = 'Status was successfully created.'
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :picture)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to '/'
  	else
  		redirect_to '/signup'
  	end
  end
  def show
  	@user = User.find(params[:id])
  
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id:session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/images/index.html.erb
<%= form_for(@images) do |f| %>
<%= f.content %>
<%= image_tag f.picture %>

<% end %>

app/views/images/new.html.erb
<%= form_for(@image, html: { multipart: true }) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>

app/views/images/show.html.erb
<%= form_for(@image) do |f| %>
<%= f.content %>
<%= image_tag f.picture %>

<% end %>

app/views/microposts/index.html.erb
<%= form_for(@microposts) do |f| %>
<%= f.content %>
<%= image_tag f.picture %>

<% end %>

app/views/microposts/new.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>

app/views/microposts/show.html.erb
<%= form_for(@micropost) do |f| %>
<%= f.content %>
<%= image_tag f.picture %>

<% end %>

app/views/static_pages/home.html.erb
sds

<%= link_to "log out", logout_path, method: "delete" %>

app/views/statuses/_form.html.erb
<%= form_for(@status, html: { multipart: true } ) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => 'ckeditor' %>
  </div>
  <div class= "field">
        <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= status.content %></td>
        <td><%= image_tag status.picture %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<div class="container">
<div class="form">
<%= form_for(@user) do |f|%>
<%= f.label :name, "NAME" %>
<%= f.text_field :name, :placeholder => "Fill name" %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit "create an acount", class: "btn-submit" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %><br>
  <%= @user.name %>
</h1>